name: checador-loginco
services:
- name: web
  dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  health_check:
    http_path: /admin/login/
  envs:
  - key: DEBUG
    value: "False"
  - key: DJANGO_SETTINGS_MODULE
    value: "checador.settings"
  - key: PYTHONUNBUFFERED
    value: "1"
  - key: SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET

databases:
- name: checador-db
  engine: PG
  version: "16"
  production: false
  cluster_name: checador-cluster
