# Generated by Django 6.0 on 2026-01-21 22:53

import checador.storage_backends
import registros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroasistencia',
            name='fecha',
            field=models.DateField(default=registros.models.fecha_mexico, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='foto_registro',
            field=models.ImageField(blank=True, null=True, storage=checador.storage_backends.MediaStorage(), upload_to='asistencias/', verbose_name='Foto de Registro'),
        ),
    ]
