# Generated by Django 6.0 on 2026-01-21 22:53

import checador.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='foto_rostro',
            field=models.ImageField(blank=True, null=True, storage=checador.storage_backends.MediaStorage(), upload_to='rostros/', verbose_name='Foto de Rostro'),
        ),
    ]
