# Generated by Django 6.0 on 2026-01-21 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0002_alter_empleado_foto_rostro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Turno')),
                ('codigo', models.CharField(choices=[('A', 'Turno A - Matutino'), ('B', 'Turno B - Vespertino'), ('C', 'Turno C - Nocturno'), ('FIJO', 'Turno Fijo')], max_length=10, unique=True, verbose_name='Código de Turno')),
                ('hora_entrada', models.TimeField(verbose_name='Hora de Entrada')),
                ('hora_salida', models.TimeField(verbose_name='Hora de Salida')),
                ('cruza_medianoche', models.BooleanField(default=False, verbose_name='Cruza Medianoche')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('color', models.CharField(default='#3B82F6', help_text='Color para visualización en dashboard (ej: #3B82F6)', max_length=7, verbose_name='Color (Hex)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, help_text='Dejar en blanco para asignación indefinida', null=True, verbose_name='Fecha de Fin')),
                ('aplica_lunes', models.BooleanField(default=True, verbose_name='Lunes')),
                ('aplica_martes', models.BooleanField(default=True, verbose_name='Martes')),
                ('aplica_miercoles', models.BooleanField(default=True, verbose_name='Miércoles')),
                ('aplica_jueves', models.BooleanField(default=True, verbose_name='Jueves')),
                ('aplica_viernes', models.BooleanField(default=True, verbose_name='Viernes')),
                ('aplica_sabado', models.BooleanField(default=False, verbose_name='Sábado')),
                ('aplica_domingo', models.BooleanField(default=False, verbose_name='Domingo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_turno', to='empleados.empleado', verbose_name='Empleado')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='turnos.turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Asignación de Turno',
                'verbose_name_plural': 'Asignaciones de Turno',
                'ordering': ['-fecha_inicio', 'empleado'],
                'indexes': [models.Index(fields=['empleado', 'fecha_inicio', 'fecha_fin'], name='turnos_asig_emplead_20fd36_idx'), models.Index(fields=['turno', 'fecha_inicio'], name='turnos_asig_turno_i_d9a247_idx')],
            },
        ),
    ]
