# Generated by Django 6.0 on 2026-01-24 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_alter_empleado_foto_rostro'),
        ('turnos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RolMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('es_descanso', models.BooleanField(default=False, verbose_name='Es Descanso')),
                ('notas', models.CharField(blank=True, max_length=100, verbose_name='Notas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_mensuales', to='empleados.empleado', verbose_name='Empleado')),
                ('turno', models.ForeignKey(blank=True, help_text='Dejar vacío para marcar como descanso', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_diarios', to='turnos.turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Rol Mensual',
                'verbose_name_plural': 'Roles Mensuales',
                'ordering': ['fecha', 'empleado'],
                'indexes': [models.Index(fields=['fecha'], name='turnos_rolm_fecha_32ea10_idx'), models.Index(fields=['empleado', 'fecha'], name='turnos_rolm_emplead_8308ce_idx')],
                'unique_together': {('empleado', 'fecha')},
            },
        ),
    ]
