# Generated by Django 6.0 on 2026-01-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_rolmensual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='codigo',
            field=models.CharField(help_text='Códigos sugeridos: A, B, C, ADMN, FIJO. Puede ingresar un código personalizado.', max_length=10, unique=True, verbose_name='Código de Turno'),
        ),
    ]
