"""
Django settings for checador project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from decouple import config
import os

# Función helper para obtener variables de entorno
def get_env(key, default=None, cast=None):
    value = os.environ.get(key, default)
    if cast and value is not None:
        if cast == bool:
            return value.lower() in ['true', '1', 'yes']
        elif cast == list:
            return [item.strip() for item in value.split(',')]
        else:
            return cast(value)
    return value

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_env('SECRET_KEY', default='django-insecure-v$$9pkjnh6_zlez9xm7odj#$6uqy8s!@*b5-_f45_gw!+@i&7c')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_env('DEBUG', default='True', cast=bool)

ALLOWED_HOSTS = get_env('ALLOWED_HOSTS', default='*', cast=list)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    # apps
    'authentication',
    'empleados',
    'horarios',
    'registros',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'checador.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'checador.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Default database configuration (SQLite for development)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / get_env('STATIC_ROOT', default='staticfiles')
STATICFILES_DIRS = [BASE_DIR / 'static']

# Whitenoise configuration for serving static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/checador/'
MEDIA_ROOT = BASE_DIR / get_env('MEDIA_ROOT', default='media/checador/')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login settings
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# Production Security Settings
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# ALLOWED_HOSTS for production
import os
if 'DIGITALOCEAN_APP_DOMAIN' in os.environ:
    ALLOWED_HOSTS.append(os.environ['DIGITALOCEAN_APP_DOMAIN'])
if 'RENDER' in os.environ:
    ALLOWED_HOSTS.append(os.environ.get('RENDER_EXTERNAL_HOSTNAME', ''))

# Database configuration from DATABASE_URL (for production)
if 'DATABASE_URL' in os.environ:
    import dj_database_url
    db_config = dj_database_url.config(
        conn_max_age=600,
        conn_health_checks=True,
    )
    # Configure SSL based on database engine
    db_engine = db_config.get('ENGINE', '')
    if 'postgresql' in db_engine:
        db_config['OPTIONS'] = {
            'sslmode': 'require',
        }
    elif 'mysql' in db_engine:
        db_config['OPTIONS'] = {
            'ssl': {'ssl-mode': 'REQUIRED'},
            'charset': 'utf8mb4',
        }
    DATABASES = {
        'default': db_config
    }

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': (
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
}

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=get_env('JWT_ACCESS_TOKEN_LIFETIME', default='60', cast=int)),
    'REFRESH_TOKEN_LIFETIME': timedelta(minutes=get_env('JWT_REFRESH_TOKEN_LIFETIME', default='1440', cast=int)),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# CORS Settings
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:8080',
    'http://127.0.0.1:8080',
    'https://checador-loginco-app-zd3ie.ondigitalocean.app/',
]

CORS_ALLOW_CREDENTIALS = True

# Configuración de Email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'apikey'
EMAIL_HOST_PASSWORD = get_env('EMAIL_HOST_PASSWORD', default='SG.uZj2N8iCTn65ZDg8v4jg3g.CgNQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g')
DEFAULT_FROM_EMAIL = 'Sistema de Checador <notificaciones@loginco.com.mx>'
# === CONFIGURACIÓN DE DIGITALOCEAN SPACES ===
# Configuración base
AWS_ACCESS_KEY_ID = config('DO_SPACES_ACCESS_KEY')
AWS_SECRET_ACCESS_KEY = config('DO_SPACES_SECRET_KEY')
AWS_STORAGE_BUCKET_NAME = config('DO_SPACES_BUCKET_NAME')
AWS_S3_ENDPOINT_URL = config('DO_SPACES_ENDPOINT_URL')  # ej: https://nyc3.digitaloceanspaces.com
AWS_S3_REGION_NAME = config('DO_SPACES_REGION', default='nyc3')

# Configuración adicional
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',  # Cache por 24 horas
}

# Configuración de permisos
AWS_DEFAULT_ACL = 'public-read'
AWS_S3_FILE_OVERWRITE = False
AWS_QUERYSTRING_AUTH = False

# Configuración de URLs personalizadas (opcional)
AWS_S3_CUSTOM_DOMAIN = config('DO_SPACES_CDN_ENDPOINT', default=None)  # CDN opcional
if AWS_S3_CUSTOM_DOMAIN:
    AWS_S3_URL_PROTOCOL = 'https:'

# === CONFIGURACIÓN DE ARCHIVOS ESTÁTICOS ===
# Backend de almacenamiento para archivos estáticos
STATICFILES_STORAGE = 'storages.backends.s3boto3.StaticS3Boto3Storage'

# Configuración específica para static files
AWS_STATIC_LOCATION = 'static'
#STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN or AWS_STORAGE_BUCKET_NAME}.{AWS_S3_ENDPOINT_URL.replace("https://", "")}/{AWS_STATIC_LOCATION}/'
STATIC_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.{AWS_S3_ENDPOINT_URL.replace("https://", "")}/{AWS_STATIC_LOCATION}/'

# === CONFIGURACIÓN DE ARCHIVOS MEDIA ===
# Backend de almacenamiento para archivos media (fotos de tickets)
DEFAULT_FILE_STORAGE = 'combustible.storage_backends.MediaStorage'  # Clase personalizada

# Configuración específica para media files
AWS_MEDIA_LOCATION = 'media/checador'
#MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN or AWS_STORAGE_BUCKET_NAME}.{AWS_S3_ENDPOINT_URL.replace("https://", "")}/{AWS_MEDIA_LOCATION}/'
MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.{AWS_S3_ENDPOINT_URL.replace("https://", "")}/{AWS_MEDIA_LOCATION}/'

# === CONFIGURACIÓN DE SEGURIDAD ===
# Headers de seguridad
AWS_S3_OBJECT_PARAMETERS.update({
    'ContentDisposition': 'inline',
    'ContentLanguage': 'es',
})

# === CONFIGURACIÓN CONDICIONAL (DESARROLLO VS PRODUCCIÓN) ===
if config('USE_SPACES', default=False, cast=bool):
    # En producción usar Spaces
    print("📦 Usando DigitalOcean Spaces para archivos")
else:
    # En desarrollo usar almacenamiento local
    STATIC_URL = '/static/'
    MEDIA_URL = '/media/checador/'
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media/checador/')
    print("📁 Usando almacenamiento local para archivos")

FILE_UPLOAD_HANDLERS = [
    'django.core.files.uploadhandler.TemporaryFileUploadHandler',
]
# === CONFIGURACIÓN PARA REPORTES ===
# Directorio específico para archivos temporales de reportes
REPORTES_TEMP_DIR = 'reportes/temp'
REPORTES_STORAGE_LOCATION = 'reportes'
