"""
Django settings for checador project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from decouple import config
import os

# Función helper para obtener variables de entorno
def get_env(key, default=None, cast=None):
    value = os.environ.get(key, default)
    if cast and value is not None:
        if cast == bool:
            return value.lower() in ['true', '1', 'yes']
        elif cast == list:
            return [item.strip() for item in value.split(',')]
        else:
            return cast(value)
    return value

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_env('SECRET_KEY', default='django-insecure-v$$9pkjnh6_zlez9xm7odj#$6uqy8s!@*b5-_f45_gw!+@i&7c')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_env('DEBUG', default='True', cast=bool)

ALLOWED_HOSTS = get_env('ALLOWED_HOSTS', default='*', cast=list)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    # apps
    'authentication',
    'empleados',
    'horarios',
    'registros',
    'turnos',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'checador.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'checador.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Configuración de base de datos desde variables individuales (.env)
DB_ENGINE = config('DB_ENGINE', default='')
if DB_ENGINE:
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': config('DB_NAME'),
            'USER': config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': config('DB_HOST'),
            'PORT': config('DB_PORT', default='3306'),
        }
    }
    # Opciones SSL para MySQL
    if 'mysql' in DB_ENGINE:
        DATABASES['default']['OPTIONS'] = {
            'ssl': {'ssl-mode': 'REQUIRED'},
            'charset': 'utf8mb4',
        }
    # Opciones SSL para PostgreSQL
    elif 'postgresql' in DB_ENGINE:
        DATABASES['default']['OPTIONS'] = {
            'sslmode': 'require',
        }
else:
    # Default: SQLite para desarrollo local
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-mx'
TIME_ZONE = 'America/Mexico_City'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
# Configuración base - puede ser sobrescrita por DigitalOcean Spaces más abajo

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / get_env('STATIC_ROOT', default='staticfiles')

# Solo incluir STATICFILES_DIRS si el directorio existe
if os.path.exists(BASE_DIR / 'static'):
    STATICFILES_DIRS = [BASE_DIR / 'static']
else:
    STATICFILES_DIRS = []

# Media files - configuración base
MEDIA_URL = '/media/checador/'
MEDIA_ROOT = BASE_DIR / get_env('MEDIA_ROOT', default='media/checador/')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login settings
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# Production Security Settings
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# ALLOWED_HOSTS for production
if 'DIGITALOCEAN_APP_DOMAIN' in os.environ:
    ALLOWED_HOSTS.append(os.environ['DIGITALOCEAN_APP_DOMAIN'])
if 'RENDER' in os.environ:
    ALLOWED_HOSTS.append(os.environ.get('RENDER_EXTERNAL_HOSTNAME', ''))

# CSRF Trusted Origins
CSRF_TRUSTED_ORIGINS = [
    'https://checador-esperanza-app-r6yoc.ondigitalocean.app',
]

# Add dynamically from environment if available
if 'DIGITALOCEAN_APP_DOMAIN' in os.environ:
    domain = os.environ['DIGITALOCEAN_APP_DOMAIN']
    if not domain.startswith('http'):
        domain = f'https://{domain}'
    if domain not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(domain)

# Database configuration from DATABASE_URL (for production)
if 'DATABASE_URL' in os.environ:
    import dj_database_url
    db_config = dj_database_url.config(
        conn_max_age=600,
        conn_health_checks=True,
    )
    # Configure SSL based on database engine
    db_engine = db_config.get('ENGINE', '')
    if 'postgresql' in db_engine:
        db_config['OPTIONS'] = {
            'sslmode': 'require',
        }
    elif 'mysql' in db_engine:
        db_config['OPTIONS'] = {
            'ssl': {'ssl-mode': 'REQUIRED'},
            'charset': 'utf8mb4',
        }
    DATABASES = {
        'default': db_config
    }

# Indicador de base de datos conectada
def _get_db_info():
    db = DATABASES['default']
    engine = db.get('ENGINE', '')
    if 'postgresql' in engine:
        db_type = 'PostgreSQL'
        icon = '🐘'
    elif 'mysql' in engine:
        db_type = 'MySQL'
        icon = '🐬'
    elif 'sqlite3' in engine:
        db_type = 'SQLite'
        icon = '📂'
    else:
        db_type = engine.split('.')[-1]
        icon = '🗄️'

    db_name = db.get('NAME', 'N/A')
    if isinstance(db_name, Path):
        db_name = db_name.name

    db_host = db.get('HOST', 'localhost')
    return icon, db_type, db_name, db_host

_icon, _db_type, _db_name, _db_host = _get_db_info()
print(f"{_icon} Base de datos: {_db_type} | Nombre: {_db_name} | Host: {_db_host}")

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': (
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
}

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=get_env('JWT_ACCESS_TOKEN_LIFETIME', default='60', cast=int)),
    'REFRESH_TOKEN_LIFETIME': timedelta(minutes=get_env('JWT_REFRESH_TOKEN_LIFETIME', default='1440', cast=int)),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# CORS Settings
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:8080',
    'http://127.0.0.1:8080',
    'https://checador-esperanza-app-r6yoc.ondigitalocean.app',
]

CORS_ALLOW_CREDENTIALS = True

# Configuración de Email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'apikey'
EMAIL_HOST_PASSWORD = get_env('EMAIL_HOST_PASSWORD', default='SG.uZj2N8iCTn65ZDg8v4jg3g.CgNQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g7Dh_jQ65g')
DEFAULT_FROM_EMAIL = 'Sistema de Checador <notificaciones@patiolaesperanza.com.mx>'
# === CONFIGURACIÓN DE DIGITALOCEAN SPACES ===
# Solo configurar si USE_SPACES está habilitado
if config('USE_SPACES', default=False, cast=bool):
    print("📦 Usando DigitalOcean Spaces para archivos")
    # Configuración base
    AWS_ACCESS_KEY_ID = config('DO_SPACES_ACCESS_KEY')
    AWS_SECRET_ACCESS_KEY = config('DO_SPACES_SECRET_KEY')
    AWS_STORAGE_BUCKET_NAME = config('DO_SPACES_BUCKET_NAME')
    AWS_S3_ENDPOINT_URL = config('DO_SPACES_ENDPOINT_URL')  # ej: https://nyc3.digitaloceanspaces.com
    AWS_S3_REGION_NAME = config('DO_SPACES_REGION', default='nyc3')

    # Configuración adicional
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',  # Cache por 24 horas
        'ContentDisposition': 'inline',
        'ContentLanguage': 'es',
    }

    # Configuración de permisos
    AWS_DEFAULT_ACL = 'public-read'
    AWS_S3_FILE_OVERWRITE = False
    AWS_QUERYSTRING_AUTH = False

    # Configuración de URLs personalizadas (opcional)
    AWS_S3_CUSTOM_DOMAIN = config('DO_SPACES_CDN_ENDPOINT', default=None)
    if AWS_S3_CUSTOM_DOMAIN:
        AWS_S3_URL_PROTOCOL = 'https:'

    # Backend de almacenamiento para archivos estáticos
    STATICFILES_STORAGE = 'storages.backends.s3boto3.StaticS3Boto3Storage'

    # Configuración específica para static files
    AWS_STATIC_LOCATION = 'static'
    STATIC_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.{AWS_S3_ENDPOINT_URL.replace("https://", "")}/{AWS_STATIC_LOCATION}/'

    # Backend de almacenamiento para archivos media
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

    # Configuración específica para media files
    AWS_MEDIA_LOCATION = 'media/checador'
    MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.{AWS_S3_ENDPOINT_URL.replace("https://", "")}/{AWS_MEDIA_LOCATION}/'
else:
    # En desarrollo usar almacenamiento local
    print("📁 Usando almacenamiento local para archivos")
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

FILE_UPLOAD_HANDLERS = [
    'django.core.files.uploadhandler.TemporaryFileUploadHandler',
]
# === CONFIGURACIÓN PARA REPORTES ===
# Directorio específico para archivos temporales de reportes
REPORTES_TEMP_DIR = 'reportes/temp'
REPORTES_STORAGE_LOCATION = 'reportes'
