# Generated by Django 6.0 on 2026-01-29 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, se enviarán los reportes semanales', verbose_name='Activo')),
                ('dia_envio', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], default=1, help_text='Día de la semana para enviar el reporte (1=Lunes, 7=Domingo)', verbose_name='Día de Envío')),
                ('hora_envio', models.TimeField(default='08:00:00', help_text='Hora del día para enviar el reporte', verbose_name='Hora de Envío')),
                ('asunto_correo', models.CharField(default='Reporte Semanal de Asistencias', max_length=255, verbose_name='Asunto del Correo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Reporte',
                'verbose_name_plural': 'Configuraciones de Reportes',
            },
        ),
        migrations.CreateModel(
            name='DestinatarioReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('nombre', models.CharField(blank=True, help_text='Nombre del destinatario (opcional)', max_length=255, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, recibirá los reportes', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Destinatario de Reporte',
                'verbose_name_plural': 'Destinatarios de Reportes',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='HistorialReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio del Periodo')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Fin del Periodo')),
                ('destinatarios', models.TextField(help_text='Lista de emails separados por coma', verbose_name='Destinatarios')),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('error', 'Error')], default='enviado', max_length=20, verbose_name='Estado')),
                ('mensaje_error', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('numero_empleados', models.IntegerField(default=0, verbose_name='Número de Empleados en Reporte')),
            ],
            options={
                'verbose_name': 'Historial de Reporte',
                'verbose_name_plural': 'Historial de Reportes',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
