# Generated by Django 6.0 on 2026-01-21 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0001_initial'),
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='turno',
            field=models.ForeignKey(blank=True, help_text='Turno asignado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios', to='turnos.turno', verbose_name='Turno'),
        ),
    ]
